# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN=:af59f8a5-c702-4cae-a104-5c6806e8c3eb
# Отправлять уведомление на почту vadim.sokolov@gmail.com (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - vadim.sokolov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
